service: updalod-image-to-s3
frameworkVersion: '3'

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:*'
          Resource: arn:aws:s3:::bucket-serverless-mkuyoc-001/*
  environment:
    BUCKET: bucket-serverless-mkuyoc-001

functions:
  signedURL:
    handler: src/aplication/signedUrl.handler
    package:
      patterns:
        - 'src/aplication/signedUrl.ts'
    events:
      - http:
          path: signedURL
          method: GET
          request:
            parameters:
              querystrings:
                filename: true
  thumbnailGenerator:
    handler: src/aplication/thumbnailGenerator.handler
    layers:
      - { Ref: BaseLambdaLayer }
    package:
      patterns:
        - 'src/aplication/thumbnailGenerator.ts'
    events:
      - s3:
          bucket: bucket-serverless-mkuyoc-001
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: upload/

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  individually: true
  patterns:
    - "!*/**"

layers:
  base:
    name: "prd-dependencies"
    compatibleRuntimes:
      - "nodejs14.x"
    package:
      artifact: app/nodejs.zip

resources:
  Resources:
    S3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        AccessControl: PublicRead
        BucketName: bucket-serverless-mkuyoc-001
    SampleBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Action:
                - 's3:GetObject'
              Effect: Allow
              Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3Bucket
                  - /*
              Principal: '*'